'use client';

import { useEffect, useState } from 'react';
import {
  accountValueLifecycle, acquisitionSteps, acquisitionTriggers, ceoFields, commercialLifecycle,
  discussionContext, discoveryByEngine, disqualificationCriteria, engineeringPlays, engineeringPrinciples,
  evidenceStates, expansionJourneys, experienceEvidence, feedbackLoop, installedBaseFields, libraryAssets,
  markets, opportunityEngines, ownershipChain, pipeline, prioritizationCriteria, products, readiness,
  roadmap, sampleExecutions, scoreDimensions, valueRealizationLoop,
  type LibraryAsset, type Product,
} from '@/data/site';
import { AccessibleModal } from '@/components/strategy/AccessibleModal';
import { CEOInputField } from '@/components/strategy/CEOInputField';
import { ExpansionPath } from '@/components/strategy/CommercialPaths';
import { EvidenceBadge } from '@/components/strategy/EvidenceBadge';
import { ExecutiveCallout } from '@/components/strategy/ExecutiveCallout';
import { GTMAssetButton, GTMAssetLibraryCard, GTMAssetModalContent } from '@/components/strategy/GTMAssetCard';
import { ProductGrowthCard } from '@/components/strategy/ProductGrowthCard';
import { SectionHeader } from '@/components/strategy/SectionHeader';

const nav = [
  ['Overview', 'overview'], ['Growth Engines', 'growth-engines'], ['Market Focus', 'market-focus'],
  ['Acquisition', 'acquisition'], ['Conversion', 'conversion'], ['Account Growth', 'account-growth'],
  ['Execution Evidence', 'execution-evidence'], ['180-Day Plan', 'plan'], ['CEO Workspace', 'workspace'],
] as const;
const STORAGE_KEY = 'algorithm-ceo-commercial-inputs-v3-1';

function readResponses() {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY); if (!raw) return null;
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    return Object.fromEntries(ceoFields.map(([key]) => [key, typeof parsed[key] === 'string' ? parsed[key] : '']));
  } catch { return null; }
}

function ProductIntelligence({ product }: { product: Product }) {
  return <div className="intelligence-body">
    <div className="intelligence-lead"><EvidenceBadge state="Documented Fact" /><p>{product.understanding}</p></div>
    <section><h3>Status quo and system boundary</h3><p><strong>{product.incumbent.system}</strong></p><p>{product.incumbent.boundary}</p><blockquote>{product.incumbent.message}</blockquote></section>
    <section><h3>Structural objections</h3><div className="objection-list">{product.objections.map(item => <details key={item.objection}><summary>{item.objection}<span>+</span></summary><p>{item.response}</p></details>)}</div></section>
    <section className="two-col"><div><h3>Diagnostic discovery</h3><ol>{product.discovery.map(item => <li key={item}>{item}</li>)}</ol></div><div><h3>Business-case inputs</h3><ul>{product.businessCase.map(item => <li key={item}>{item}</li>)}</ul><p className="guardrail">Use only customer-provided or independently verified inputs.</p></div></section>
    <section><h3>Competitive boundary</h3><div className="comparison-grid">{product.competitors.map(item => <article key={item.name}><h4>{item.name}</h4><p><b>Where stronger</b>{item.stronger}</p><p><b>Commercial wedge</b>{item.wedge}</p><p><b>Do not claim</b>{item.avoid}</p></article>)}</div></section>
    <ExecutiveCallout><p>{product.gaps.join(' · ')}</p></ExecutiveCallout>
  </div>;
}

function SampleExecutionContent() {
  const [active, setActive] = useState(0); const item = sampleExecutions[active];
  return <div className="sample-execution">
    <div className="modal-tabs" role="tablist" aria-label="Sample sales execution engines">{sampleExecutions.map((entry, index) => <button key={entry.engine} type="button" role="tab" aria-selected={active === index} onClick={() => setActive(index)}>{entry.engine}</button>)}</div>
    <article role="tabpanel"><header><div><EvidenceBadge state="Commercial Hypothesis" /><p className="research-label">Research Target — Not a customer or active opportunity</p><h3>{item.target}</h3><p>{item.industry}</p></div><div className="score-orbit"><strong>{item.score}</strong><span>/ 100</span><small>{item.scoreDetail}</small></div></header>
      <div className="execution-grid"><div><b>Verified trigger</b><p>{item.trigger}</p><small>{item.evidence}</small></div><div><b>Buyer map</b><p>{item.buyers}</p></div><div><EvidenceBadge state="Documented Fact" /><p>{item.fact}</p></div><div><EvidenceBadge state="Commercial Hypothesis" /><p>{item.hypothesis}</p></div><div className="wide"><b>Discovery question</b><p>{item.question}</p></div><div><b>Enterprise entry wedge</b><p>{item.wedge}</p></div><div><b>Proof required</b><p>{item.proof}</p></div><div className="wide"><b>How account value could grow</b><p>{item.growth}</p></div><div><b>What could kill it</b><p>{item.kill}</p></div><div><b>Next best action</b><p>{item.next}</p></div></div>
    </article>
  </div>;
}

export default function StrategySite() {
  const [menuOpen, setMenuOpen] = useState(false); const [activeSection, setActiveSection] = useState('overview');
  const [activeProduct, setActiveProduct] = useState(0); const [activeMarket, setActiveMarket] = useState(0);
  const [activeDiscovery, setActiveDiscovery] = useState(0); const [activePipeline, setActivePipeline] = useState(0);
  const [activeJourney, setActiveJourney] = useState(0); const [activePlan, setActivePlan] = useState(0);
  const [productModal, setProductModal] = useState<Product | null>(null); const [assetModal, setAssetModal] = useState<LibraryAsset | null>(null);
  const [sampleModal, setSampleModal] = useState(false); const [summaryModal, setSummaryModal] = useState(false);
  const [responses, setResponses] = useState<Record<string, string>>({}); const [editing, setEditing] = useState(true);
  const [scores, setScores] = useState<Record<string, number>>(() => Object.fromEntries(scoreDimensions.map(item => [item.name, 0])));
  const [readinessState, setReadinessState] = useState<Record<string, string>>(() => Object.fromEntries(readiness.map(item => [item, 'CEO Input Required'])));
  const product = products[activeProduct]; const totalScore = scoreDimensions.reduce((sum, item) => sum + (scores[item.name] || 0), 0);
  const answered = ceoFields.filter(([key]) => responses[key]?.trim()); const missing = ceoFields.filter(([key]) => !responses[key]?.trim());

  useEffect(() => {
    const saved = readResponses(); if (!saved) return;
    const timer = window.setTimeout(() => { setResponses(saved); setEditing(false); }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { const visible = entries.filter(e => e.isIntersecting).sort((a,b) => b.intersectionRatio-a.intersectionRatio)[0]; if (visible) setActiveSection(visible.target.id); }, { rootMargin: '-20% 0px -68% 0px', threshold: [0,.25] });
    nav.forEach(([,id]) => { const element = document.getElementById(id); if (element) observer.observe(element); }); return () => observer.disconnect();
  }, []);

  const save = () => { try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(Object.fromEntries(ceoFields.map(([key]) => [key, responses[key] || ''])))); } catch {} setEditing(false); setSummaryModal(true); };
  const clear = () => { if (!window.confirm('Clear all saved CEO responses from this device?')) return; try { window.localStorage.removeItem(STORAGE_KEY); } catch {} setResponses({}); setEditing(true); };
  const exportResponses = () => { const lines = ['THE ALGORITHM — CEO COMMERCIAL DISCOVERY RESPONSES', '']; ceoFields.forEach(([key,label]) => lines.push(label, responses[key]?.trim() || 'CEO Input Required', '')); const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain'})); const a=document.createElement('a'); a.href=url; a.download='the-algorithm-ceo-responses.txt'; a.click(); URL.revokeObjectURL(url); setSummaryModal(true); };
  const cycleReadiness = (name: string) => { const states=['CEO Input Required','Partial','Validated']; setReadinessState(current => ({...current,[name]:states[(states.indexOf(current[name])+1)%states.length]})); };

  return <>
    <a className="skip-link" href="#main-content">Skip to content</a>
    <nav className="nav" aria-label="Primary navigation"><a className="brand" href="#overview"><span className="brand-mark">A</span><span>The Algorithm<small>Commercial Growth Architecture</small></span></a><div className="nav-links">{nav.map(([label,id]) => <a key={id} className={activeSection===id?'active':''} href={`#${id}`}>{label}</a>)}</div><div className="nav-secondary"><button type="button" onClick={() => setSampleModal(true)}>Sample Sales Execution</button><a href="#library">GTM Library</a></div><button className="menu-button" type="button" aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={() => setMenuOpen(v=>!v)}><span/><span/><span/><b className="sr-only">Toggle navigation</b></button><div id="mobile-menu" className={`mobile-menu${menuOpen?' open':''}`}>{nav.map(([label,id]) => <a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{label}</a>)}<button type="button" onClick={()=>{setSampleModal(true);setMenuOpen(false)}}>Sample Sales Execution</button><a href="#library" onClick={()=>setMenuOpen(false)}>GTM Library</a></div></nav>
    <main id="main-content">
      <section className="hero shell" id="overview"><div><p className="eyebrow"><span/>Evidence-led commercial operating system</p><h1>The Algorithm<br/><em>Commercial Growth Architecture</em></h1><p className="hero-deck">A unified approach to enterprise entry, qualified opportunity creation, conversion, account expansion and long-term customer value across products and regulated engineering.</p><div className="hero-actions"><a className="button primary" href="#growth-engines">Explore the Commercial Architecture</a><button className="button outline" type="button" onClick={()=>setAssetModal(libraryAssets[5])}>View Executive Brief</button><a className="text-link" href="#workspace">Review CEO Inputs</a></div></div><aside className="hero-system"><p className="data-label">One commercial architecture</p><blockquote>Products create entry. Implementation creates insight. Engineering creates depth. Managed infrastructure creates continuity. Customer success creates expansion.</blockquote><ExpansionPath steps={['Enter','Prove value','Expand scope','Deepen account','Retain']} /></aside></section>

      <section className="section-space shell known-section"><SectionHeader index="01" label="Commercial opportunity" title="The capability exists. The opportunity is to make growth systematic." copy="This is not a collection of disconnected offers. It is one evidence-led system for deciding where to focus, what to prove and how to grow account value."/><div className="opportunity-grid">{opportunityEngines.map(item=><article key={item.name}><span>{item.number}</span><h3>{item.name}</h3><p>{item.detail}</p></article>)}</div><div className="evidence-grid">{discussionContext.map((item,index)=><article key={index}><EvidenceBadge state={item.state}/><p>{item.text}</p></article>)}</div><div className="evidence-legend">{evidenceStates.map(item=><div key={item.state}><EvidenceBadge state={item.state}/><p>{item.meaning}</p></div>)}</div></section>

      <section className="architecture section-space" id="growth-engines"><div className="shell"><SectionHeader index="02" label="Unified commercial growth architecture" title="Understand. Prioritize. Identify. Engage. Diagnose. Convert. Expand. Retain." copy="Every motion connects market truth, account evidence, proof and post-contract ownership."/><div className="lifecycle">{commercialLifecycle.map(([name,output],i)=><article key={name}><span>{String(i+1).padStart(2,'0')}</span><h3>{name}</h3><p>{output}</p></article>)}</div><div className="account-lifecycle"><p>Account-value lifecycle</p><ExpansionPath steps={accountValueLifecycle.map(([name])=>name)}/></div></div></section>

      <section className="products section-space shell"><SectionHeader index="03" label="Product growth engines" title="Three products. Distinct entry motions. One account-growth system." copy="Each product enters through a contained operational problem, establishes customer-specific proof and expands only when scale or complexity creates a legitimate requirement."/><div className="product-tabs" role="tablist">{products.map((item,i)=><button key={item.id} type="button" role="tab" aria-selected={activeProduct===i} className={activeProduct===i?'active':''} onClick={()=>setActiveProduct(i)}><span>0{i+1}</span><strong>{item.name}</strong><small>{item.label}</small></button>)}</div><ProductGrowthCard product={product} asset={libraryAssets.find(a=>a.id===product.assetId)!} onViewIntelligence={setProductModal} onOpenAsset={setAssetModal}/></section>

      <section className="engineering section-space"><div className="shell"><SectionHeader index="04" label="Regulated Engineering & Modernization" title="Outcome, not capacity." copy="Lead with a technically difficult, regulated and expensive-to-get-wrong business problem—not a generic developer bench."/><div className="engineering-principles">{engineeringPrinciples.map((item,i)=><article key={item}><span>0{i+1}</span><p>{item}</p></article>)}</div><div className="engineering-list">{engineeringPlays.map((play,i)=><details key={play.name} open={i===0}><summary><span>0{i+1}</span><strong>{play.name}</strong><em>{play.entry}</em><i>+</i></summary><div><p><small>Verifiable trigger</small>{play.trigger}</p><p><small>Likely buyer</small>{play.buyer}</p><p><small>Entry assessment</small>{play.entry}</p></div></details>)}</div><div className="engineering-asset"><ExecutiveCallout state="Commercial Hypothesis"><p>Compliance-by-architecture can differentiate when identity, access, encryption, residency, logging, lineage, change control, recovery and evidence enter before implementation.</p></ExecutiveCallout><GTMAssetButton asset={libraryAssets[3]} onOpen={setAssetModal}/></div></div></section>

      <section className="markets section-space" id="market-focus"><div className="shell"><SectionHeader index="05" label="Market & industry prioritization" title="Market opportunity tells us where to investigate. Triggers determine where we act." copy="US and UAE are Priority 1. UK and India are Priority 2 subject to product applicability; clinIQ remains excluded from India."/><div className="market-layout"><div className="market-tabs" role="tablist">{markets.map((market,i)=><button key={market.name} type="button" role="tab" aria-selected={activeMarket===i} className={activeMarket===i?'active':''} onClick={()=>setActiveMarket(i)}><span>{market.priority}</span><strong>{market.name}</strong><small>{market.engines}</small></button>)}</div><article className="market-panel" role="tabpanel"><header><EvidenceBadge state="Commercial Hypothesis"/><h3>{markets[activeMarket].name}</h3><p>{markets[activeMarket].engines}</p></header><dl><div><dt>Industry focus</dt><dd>{markets[activeMarket].verticals}</dd></div><div><dt>Buyer dynamics</dt><dd>{markets[activeMarket].dynamics}</dd></div><div><dt>Route to market</dt><dd>{markets[activeMarket].route}</dd></div><div><dt>Indicator</dt><dd>{markets[activeMarket].indicator}</dd></div><div><dt>Ecosystem routes</dt><dd>{markets[activeMarket].partners}</dd></div></dl></article></div></div></section>

      <section className="accounts section-space" id="acquisition"><div className="shell"><SectionHeader index="06" label="Trigger-based account acquisition" title="No trigger, no Tier A." copy="ICP identifies who. A verified trigger identifies when. Account intelligence explains why. Discovery tests whether the hypothesis is true."/><ExpansionPath steps={acquisitionSteps}/><div className="trigger-cards">{acquisitionTriggers.map(item=><article key={item.engine}><h3>{item.engine}</h3><ol>{item.triggers.map(x=><li key={x}>{x}</li>)}</ol></article>)}</div><div className="score-readiness"><article className="score-card"><div className="score-total"><span>Evidence-backed account score</span><strong>{totalScore}</strong><small>/ 100</small><p>{totalScore>=80?'Tier A only when a credible trigger and buyer path also exist.':totalScore>=60?'Tier B: targeted nurture and evidence monitoring.':totalScore>=40?'Tier C: monitor without heavy presales investment.':'Deprioritize.'}</p></div>{scoreDimensions.map(item=><label key={item.name}><span><strong>{item.name}</strong><small>{item.evidence}</small></span><input type="range" min="0" max={item.weight} value={scores[item.name]} onChange={e=>setScores(c=>({...c,[item.name]:Number(e.target.value)}))}/><b>{scores[item.name]} / {item.weight}</b></label>)}</article><article className="readiness-card"><header><p className="data-label">Commercial readiness & proof audit</p><h3>Do not sell beyond current proof.</h3><p>Select each status to cycle through the evidence states.</p></header>{readiness.map(item=><button key={item} type="button" onClick={()=>cycleReadiness(item)}><span>{item}</span><b className={`status-${readinessState[item].toLowerCase().replaceAll(' ','-')}`}>{readinessState[item]}</b></button>)}</article></div><div className="acquisition-actions"><button className="button primary" type="button" onClick={()=>setSampleModal(true)}>Sample Sales Execution</button><p>Four current research-target examples demonstrate selection, evidence, discovery and expansion mechanics without implying customer status or buying intent.</p></div></div></section>

      <section className="discovery section-space shell" id="conversion"><SectionHeader index="07" label="Strategic discovery, business case & conversion" title="No demo before diagnosis. No proposal before quantified impact." copy="FACT → HYPOTHESIS → DISCOVERY QUESTION protects the commercial process from invented pain and premature product pitching."/><div className="fact-rule"><strong>FACT</strong><i>→</i><strong>HYPOTHESIS</strong><i>→</i><strong>DISCOVERY QUESTION</strong></div><div className="discovery-layout"><div className="discovery-tabs" role="tablist">{discoveryByEngine.map((item,i)=><button key={item.name} type="button" role="tab" aria-selected={activeDiscovery===i} className={activeDiscovery===i?'active':''} onClick={()=>setActiveDiscovery(i)}>{item.name}</button>)}</div><article className="discovery-panel" role="tabpanel"><section><p className="data-label">Questions that earn the right to proceed</p><ol>{discoveryByEngine[activeDiscovery].questions.map(q=><li key={q}>{q}</li>)}</ol></section><div><span>Business-case discipline</span><p>{discoveryByEngine[activeDiscovery].formula}</p></div></article></div><div className="pipeline-layout"><div className="pipeline-tabs" role="tablist">{pipeline.map((stage,i)=><button key={stage.name} type="button" role="tab" aria-selected={activePipeline===i} className={activePipeline===i?'active':''} onClick={()=>setActivePipeline(i)}><span>0{i+1}</span><strong>{stage.name}</strong></button>)}</div><article className="pipeline-panel" role="tabpanel"><h3>{pipeline[activePipeline].name}</h3><dl><div><dt>Entry</dt><dd>{pipeline[activePipeline].entry}</dd></div><div><dt>Required evidence</dt><dd>{pipeline[activePipeline].evidence}</dd></div><div><dt>Exit</dt><dd>{pipeline[activePipeline].exit}</dd></div><div><dt>False positive</dt><dd>{pipeline[activePipeline].falsePositive}</dd></div></dl></article></div></section>

      <section className="expansion section-space" id="account-growth"><div className="shell"><SectionHeader index="08" label="Account growth & customer success" title="The first win should create insight—not just revenue." copy="Cross-sell only when implementation, scale, architecture, data, compliance or operations expose a legitimate adjacent problem."/><div className="journey-tabs" role="tablist">{expansionJourneys.map((item,i)=><button key={item.name} type="button" role="tab" aria-selected={activeJourney===i} className={activeJourney===i?'active':''} onClick={()=>setActiveJourney(i)}>{item.name}</button>)}</div><ExpansionPath steps={expansionJourneys[activeJourney].steps}/><div className="installed-block"><h3>Existing-account expansion audit</h3><p>Do not invent account names, revenue or cross-sell opportunities. Investigate the next legitimate problem using internal evidence.</p><div className="installed-grid">{installedBaseFields.map((field,i)=><div key={field}><span>{String(i+1).padStart(2,'0')}</span><p>{field}</p></div>)}</div></div><div className="loop-grid"><article><p>Customer insight → stronger GTM</p><ExpansionPath dense steps={feedbackLoop}/></article><article><p>Post-contract value realization</p><ExpansionPath dense steps={valueRealizationLoop}/></article></div></div></section>

      <section className="execution section-space shell" id="execution-evidence"><SectionHeader index="09" label="Relevant commercial execution evidence" title="Evidence of ownership without turning the site into a résumé." copy="The cases are intentionally anonymized. They show how commercial requirements were translated into practical product, engineering and adoption work."/><div className="case-grid">{experienceEvidence.map((item,i)=><article key={item.industry}><span>0{i+1}</span><h3>{item.industry}</h3><dl><div><dt>Requirement</dt><dd>{item.requirement}</dd></div><div><dt>Challenge</dt><dd>{item.challenge}</dd></div><div><dt>Commercial approach</dt><dd>{item.approach}</dd></div><div><dt>Outcome</dt><dd>{item.outcome}</dd></div><div><dt>Relevance</dt><dd>{item.relevance}</dd></div></dl></article>)}</div><div className="why-win"><article><h3>Why The Algorithm can win</h3><p>Product IP + regulated-domain understanding + custom engineering + integration capability + cloud and managed infrastructure + technical leadership.</p><EvidenceBadge state="Commercial Hypothesis"/></article><article><h3>Prioritize when</h3><ul>{prioritizationCriteria.map(x=><li key={x}>{x}</li>)}</ul></article><article><h3>Disqualify when</h3><ul>{disqualificationCriteria.map(x=><li key={x}>{x}</li>)}</ul></article></div></section>

      <section className="ownership section-space"><div className="shell"><SectionHeader index="10" label="Commercial ownership & collaboration" title="Responsibility continues after the initial contract." copy="The operating boundary protects commercial independence while respecting where technical leadership must remain engaged."/><ExpansionPath dense steps={ownershipChain}/><div className="ownership-boundary"><article><h3>Commercial leader independently owns</h3><p>Market strategy, prioritization, outreach, discovery, qualification, business case, proposal coordination, negotiation, account growth, customer-success cadence and commercial intelligence.</p></article><article><h3>Founder / technical leadership engages where appropriate</h3><p>Architecture validation, roadmap commitments, security/compliance validation, custom-engineering estimation, major workshops and strategic executive sponsorship.</p></article></div></div></section>

      <section className="roadmap section-space" id="plan"><div className="shell"><SectionHeader index="11" label="180-day single-owner execution plan" title="Validate. Build. Create traction. Convert. Expand. Systemize." copy="The plan commits to evidence and operating discipline—not arbitrary revenue, hiring or conversion promises."/><div className="roadmap-tabs" role="tablist">{roadmap.map((item,i)=><button key={item.range} type="button" role="tab" aria-selected={activePlan===i} className={activePlan===i?'active':''} onClick={()=>setActivePlan(i)}><span>Days {item.range}</span><strong>{item.phase}</strong></button>)}</div><article className="roadmap-panel" role="tabpanel"><header><p>Days {roadmap[activePlan].range}</p><h3>{roadmap[activePlan].phase}</h3></header><ol>{roadmap[activePlan].items.map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol></article></div></section>

      <section className="workspace section-space shell" id="workspace"><SectionHeader index="12" label="CEO commercial discovery workspace" title="Replace assumptions with internal company truth." copy="Responses saved on this device repopulate after refresh. Unanswered fields remain CEO Input Required."/><div className="workspace-toolbar"><div><span>{answered.length} answered</span><span>{missing.length} remaining</span></div><div><button type="button" onClick={()=>setEditing(true)}>Edit</button><button className="primary" type="button" onClick={save}>{editing?'Save Responses':'Update Responses'}</button><button type="button" onClick={exportResponses}>Export Responses</button><button type="button" onClick={clear}>Clear</button></div></div><div className="workspace-grid">{ceoFields.map(([key,label],i)=><CEOInputField key={key} fieldKey={key} index={i} label={label} value={responses[key]||''} disabled={!editing} onChange={value=>setResponses(c=>({...c,[key]:value}))}/>)}</div><p className="privacy-note">Responses are saved only on this browser and device. Unanswered fields are not interpreted as conclusions.</p></section>

      <section className="library section-space" id="library"><div className="shell"><SectionHeader index="13" label="GTM Intelligence Library" title="The website is the operating system. The assets carry the detail." copy="Open any asset for an executive synopsis, key sections and an in-site document preview. Downloads use the original source files."/><div className="library-list">{libraryAssets.map((asset,i)=><GTMAssetLibraryCard key={asset.id} asset={asset} index={i} onOpen={setAssetModal}/>)}</div></div></section>
      <section className="closing"><div className="shell"><p className="section-index">14 / Executive close</p><h2>The next stage is not about doing more sales activity.</h2><p>It is about building a commercial system that knows where to focus, why a customer should act, how to prove value, how to convert the right opportunities and how to grow the relationship after the first win.</p><div><a className="button primary" href="#workspace">Review CEO Inputs</a><a className="button outline" href="#library">Explore the GTM Library</a></div></div></section>
    </main>
    <footer className="site-footer"><div className="shell"><div className="brand"><span className="brand-mark">A</span><span>The Algorithm<small>Commercial Growth Architecture</small></span></div><p>Evidence-led strategy · No revenue forecast</p><a href="#overview">Back to top ↑</a></div></footer>

    <AccessibleModal open={Boolean(productModal)} title={`${productModal?.name||''} Enterprise Strategy`} onClose={()=>setProductModal(null)} wide>{productModal&&<ProductIntelligence product={productModal}/>}</AccessibleModal>
    <AccessibleModal open={Boolean(assetModal)} title={assetModal?.name||''} eyebrow="GTM intelligence asset" onClose={()=>setAssetModal(null)} wide>{assetModal&&<GTMAssetModalContent asset={assetModal}/>}</AccessibleModal>
    <AccessibleModal open={sampleModal} title="Sample Sales Execution" eyebrow="Research targets · proof of execution" onClose={()=>setSampleModal(false)} wide><SampleExecutionContent/></AccessibleModal>
    <AccessibleModal open={summaryModal} title="Responses Saved" eyebrow="CEO workspace summary" onClose={()=>setSummaryModal(false)}><div className="workspace-summary"><div><strong>{answered.length}</strong><span>Answered fields</span></div><div><strong>{missing.length}</strong><span>Remaining information gaps</span></div><section><h3>Answered areas</h3>{answered.length?<ul>{answered.map(([,label])=><li key={label}>{label}</li>)}</ul>:<p>No responses have been captured.</p>}</section><section><h3>Suggested next discussion topics</h3>{missing.length?<ul>{missing.slice(0,6).map(([,label])=><li key={label}>{label}</li>)}</ul>:<p>Review all responses with leadership before treating them as confirmed operating truth.</p>}</section><p>No conclusion has been generated from unanswered fields.</p><div><button type="button" onClick={()=>{setSummaryModal(false);setEditing(true)}}>Edit</button><button type="button" onClick={exportResponses}>Export</button><button className="primary" type="button" onClick={()=>setSummaryModal(false)}>Close</button></div></div></AccessibleModal>
  </>;
}
